### PR TITLE
Casting recipes now require their original recipes' tech to unlock

### LINKED ISSUE #17: [BUG] More Casting & Molten Tungsten recipes are all unlocked at the Foundry, allowing you to skip researching certain recipes
image
E.G. I haven't researched artillery yet, but the casting recipe allows me to make the artillery turret anyway
It should probably move the unlock of the recipe to the same tech as its source recipe instead of shoving them all onto Foundries

### PR DESCRIPTION
**Pull request by Samario1**
Fixes #17

### CODE REVIEW

**Comment by LuziferSenpai** [comment]
I dont want to have them to use there original tech, I made it on purpose into the foundry tech.

**Comment by Samario1** [comment]
Would you at least consider having this as an off by default startup option?

**Comment by LuziferSenpai** [comment]
https://github.com/LuziferSenpai/factorio-mods/commit/8e9511d2c79bc908e5337bb31735688752f12479

**Comment by Samario1** [comment]
👍

**Pull request closed without merging**
